<p>
<a href="/imagedb/commission/form">Opret</a>
</p>
<table>
	<thead>
		<tr>
			<td>Aktiv</td>
			<td>Valgt</td>
			<td>Overskrift</td>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->entries as $entry): ?>
        <tr>
        	<td><input type="checkbox" class="commission_active" value="<?=$entry->id?>"<?php if ($entry->active > 0) { echo ' checked="checked"'; } ?> />
        	<td><input type="checkbox" class="commission_choose" value="<?=$entry->id?>"<?php if ($this->chosen == $entry->id) { echo ' checked="checked"'; } ?> />
        	<td><a href="/imagedb/commission/form?id=<?=$entry->id?>"><?=$entry->name?></a></td>
        </tr>
        <?php endforeach ?>
	</tbody>
</table>