<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>
 
<body>
	<div class="strip">
		<ul>
			<li><a href="/">home</a></li>
			<li><a href="/imagedb" class="imagedb">images</a></li>
			<li><a href="/admin/teaser">frontpage</a></li>
			<li><a href="/admin/text">texts</a></li>
			<?php if ($this->logout){ ?>
	       		<li><a href="/admin/logout">log out</a></li> 
	       	<?php } ?>
		</ul>
	</div>
	<div class="container content">
		<?php echo $this->layout()->content; ?>
	</div>
</body>
</html>