<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->headScript(); ?>
</head>
 
<body>
	<div class="strip container">
		<ul id="menu">
			<li><a href="/">Om Nyd Livet</a></li>
			<li><a href="/">Kurser</a></li>
			<li><a href="/">Aktiviteter</a></li>
			<li><a href="/">Kontakt</a></li>
		</ul>
	</div>
